Added `PyErr::add_note`
